server:
  port: 80
---
spring:
  profiles: local
server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: real
server:
  port: 8082
---
datasource:
  url: jdbc:h2:mem:userdb
spring:
  h2:
    console:
      enabled: true