spring:
  #  datasource:
  #    url: jdbc:mysql://
  #    username:
  #    password:
  #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1093010447426-6uh6vdc6ss3nnjmhdhhrhcjf1gp5foe9.apps.googleusercontent.com
            client-secret: NfQxg8vapYITHgtdCjsdjrY1
          facebook:
            client-id: 564162601158748
            client-secret: dd56c82cf93b958f1d00e30b355df0c2
custom:
  oauth2:
    kakao:
      client-id: 0a7ca146321bc1d63285c916ab12134c
